import "./globals.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// import Head from "next/head";
// // ...existing code...
// <Head>
//   <link rel="icon" href="/logo.png" />
// </Head>;

export const metadata = {
  title: "Mburubu Construction",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
